### PR TITLE
fix: interactive completion for fish

### LINKED ISSUE #341: Can't select in interactive completion on fish shell
when type `z foo<space><tab>` fzf opens and after selected one, it doesn't show on commandline

it works on zsh

### PR DESCRIPTION
**Pull request by NextAlone**
Just as mentioned in #341, use `\#` to indicate full path for zoxide to query.

In my tests it worked well.

resolved #341

### CODE REVIEW

**Comment by NextAlone** [comment]
Thanks for your work.

**Comment by hferreira23** [comment]
@ajeetdsouza when do you expect to release a new version with this fix (pretty please)?

**Comment by antoyo** [comment]
> @ajeetdsouza when do you expect to release a new version with this fix (pretty please)?

I'm wondering the same. It would be nice to have zoxide works correctly with fish.
Thanks for your work.

**Comment by NextAlone** [comment]
> > @ajeetdsouza when do you expect to release a new version with this fix (pretty please)?
> 
> I'm wondering the same. It would be nice to have zoxide works correctly with fish.
> Thanks for your work.

maybe you install an git version for now？

**Comment by ajeetdsouza** [comment]
@hferreira23 @antoyo I just released v0.8.2.

**Comment by Zesko** [comment]
The version 0.8.2 works now for me using Fish shell version 3.4.1. Thanks!

I don't know if it works with Fish shell 3.5.0.

**Comment by ajeetdsouza** [comment]
Yeap, seems to be working fine for me.

**Comment by antoyo** [comment]
I just tested version 0.8.2 and it seems to misbehave.
For instance, when I type `z tmp <TAB>` it completes to: `z tmp z\#/tmp`.
Do I need to do anything after an upgrade to make it work?
I use fish version 3.4.1 with zoxide v0.8.2.

**Comment by NextAlone** [comment]
> I just tested version 0.8.2 and it seems to misbehave.
> For instance, when I type `z tmp <TAB>` it completes to: `z tmp z\#/tmp`.
> Do I need to do anything after an upgrade to make it work?
> I use fish version 3.4.1 with zoxide v0.8.2.

it means only this path match

**Comment by antoyo** [comment]
> it means only this path match

So, the behavior changed?
It used to complete to `z /tmp`; why is there the `z\#` prefix and why doesn't it delete the query (`tmp`)?

**Comment by NextAlone** [comment]
> > it means only this path match
> 
> So, the behavior changed? It used to complete to `z /tmp`; why is there the `z\#` prefix and why doesn't it delete the query (`tmp`)?

Oh, yes, the method before doesnt work on some system

**Comment by antoyo** [comment]
So, you're saying this behavior is expected?

Any way to at least delete the query `tmp` so that pressing enter actually go to the directory that was completed?

**Comment by Zesko** [comment]
`z#/tmp` without `\` like the description in ReadMe.
Screenshot_20220627_145741

VS.

`z\#/tmp` with `\`
Screenshot_20220627_145712

`\#` seems the color.  I didn't change the color at all. 
But I think Fish may recognized `\#` and defined color for it.

**Comment by NextAlone** [comment]
because fish will escape `\#` to `#`, and single `#` is not allowed

**Comment by antoyo** [comment]
> Pressing enter will go to the directory that was completed. The `z#` prefix ensures that this happens.

Unfortunately, it doesn't: I get the following error:
```
~ $ z tmp z\#/tmp
zoxide: no match found
```
If I delete the query, it does work:
```
~ $ z z\#/tmp
/tmp $
```
But I'd rather avoid delete the query manually.

**Comment by NextAlone** [comment]
➜ fish --version
fish, version 3.5.0-47-gfee5a9125

➜ zoxide --version
zoxide v0.8.2

**Comment by Zesko** [comment]
Screenshot_20220627_151127

It works for me using Fish shell 3.4.1 with Starship too.

**Comment by antoyo** [comment]
Oh, the issue comes from my alias of `z`. It indeed works if I remove that alias.

**Comment by ajeetdsouza** [comment]
The `z\#` is now a `z!`, which looks a lot cleaner. Unfortunately, I don't think Fish supports a way to quote the completion rather than escape it, so instead of `z "z!/some directory/"` we end up getting `z z!/some\ directory/`.

**Pull request merged**
