### PR TITLE
Add Winget Releaser workflow

### PR DESCRIPTION
**Pull request by sitiom**
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.

example

2. Fork https://github.com/microsoft/winget-pkgs under @ajeetdsouza . The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

You can test out the action inputs in this [playground](https://bittu.eu.org/docs/wr-playground).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been created with WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+created+with+WinGet+Releaser).

- Related to #79

### CODE REVIEW

**Comment by ajeetdsouza** [comment]
Sorry for the late reply! Why do we need to add a Dependabot config?

**Comment by sitiom** [comment]
It would be nice to keep the dependencies up to date. For example, Winget Releaser `v1` isn't working due to https://github.com/vedantmgoyal2009/winget-releaser/issues/86, yet many repos are still using the outdated version.

**Comment by sitiom** [comment]
@ajeetdsouza Bump

**Comment by ajeetdsouza** [comment]
Thanks, sorry I missed this!

**Comment by sitiom** [comment]
Manually made a PR for now: https://github.com/microsoft/winget-pkgs/pull/106175

**Comment by ajeetdsouza** [comment]
I appreciate that, thank you!

**Comment by sitiom** [comment]
- https://github.com/microsoft/winget-pkgs/pull/115249

**Pull request merged**
