### PR TITLE
Add --exit-0 to fzf

### PR DESCRIPTION
**Pull request by xeruf**
So there is no prompt if there is no match

### CODE REVIEW

**Comment by xeruf** [comment]
Second commit adds a preview

**Comment by ajeetdsouza** [comment]
Hey @xeruf, you might want to use the `_ZO_FZF_OPTS` environment variable (see `zoxide --help` for details). Regarding the changes you've suggested, I don't think we can merge them because:

- The preview window looks great, but it doesn't work on Windows. However, I might add it to the wiki as a "common configuration".
- The `--exit-0` switch may not work for everyone - for example, I mainly use `zi` for browsing the database, and the experience can be jarring if I'm expecting an interactive window to open up but it doesn't.

I'll close this PR for now, but I'd love to hear any thoughts you have.

**Comment by xeruf** [comment]
>     * The preview window looks great, but it doesn't work on Windows. However, I might add it to the wiki as a "common configuration".

I guess we could test whether `ls` is available and otherwise use whatever there is on windows instead.

>     * The `--exit-0` switch may not work for everyone - for example, I mainly use `zi` for browsing the database, and the experience can be jarring if I'm expecting an interactive window to open up but it doesn't.

so you are expecting an empty window to open?

**Comment by ajeetdsouza** [comment]
> I guess we could test whether ls is available and otherwise use whatever there is on windows instead.

On my system, I use `exa` instead of `ls`. This is why I want to leave this as a user-configurable option, rather than hardcoding it ourselves.

> so you are expecting an empty window to open?

I suppose it's the equivalent of opening an empty file with `less`. For that matter, even `--select-1` might have been useful, but for someone who just wants to browse the database, it doesn't work as well.

---

For now, I think a better way would be to add these flags as a section under `Configuration` in the README, and let users customize `_ZO_FZF_OPTS` themselves.

**Pull request closed without merging**
