### PR TITLE
support autocd option

### PR DESCRIPTION
**Pull request by solodov**
In bash, when autocd option is set and user enters a directory name as a command, it results in a very specific call to cd:

cd -- [directory name]

zoxide's directory changing function passes all arguments to __zoxide_z as is, including the "--" first argument. By detecting this and skipping the first argument changing directory works with autocd set.

This particular bug only happens when initializing zoxide with `--cmd cd`. Here's how it breaks in bash:

```bash
$ shopt -c autocd
$ eval $(zoxide init --cmd cd bash)"
$ ..
cd -- ..
zoxide: no match found
```

### CODE REVIEW

**Comment by PhoenixmitX** [comment]
would love to see this merge

**Comment by solodov** [comment]
As far as I can tell this PR is ready for merging. Let me know if there's anything missing.

**Comment by german-moreno283** [comment]
Would this work for zsh as well?

**Comment by solodov** [comment]
> Would this work for zsh as well?

I updated initial comment with the reproduction steps for bash. Checked in zsh and seems to work correctly already:

```zsh
% setopt  autocd
% eval "$(zoxide init --cmd cd zsh)"
% /
```

**Comment by charlesbvll** [comment]
@ajeetdsouza Is there any update on this? Seems like a very useful feature to have!

**Comment by solodov** [comment]
> @ajeetdsouza Is there any update on this? Seems like a very useful feature to have!

PR is ready to be merged, as far as I'm concerned. I've been using this fix for a few months now, everything seems to be ok.

**Comment by fwam** [comment]
bump

**Comment by tonyOehme** [comment]
This seems like a neat improvement. @ajeetdsouza any updates on this?

**Comment by ajeetdsouza** [comment]
Thank you, and sorry about the delay!

**Pull request merged**
