### PR TITLE
New installer options (v2)

### PR DESCRIPTION
**Pull request by aarondill**
This is a rewrite of #590 to reduce the diff and make it a more reasonable pr.

Add support for options in install script

This adds support for serveral new command line options (taken from the usage):
    - `-b, --bin-dir   Override the bin installation directory`
    - `-m, --man-dir   Override the man installation directory`
    - `-a, --arch      Override the architecture identified by the installer`
    - `-h, --help      Display this help message`
This also (coincidentally) allows for $BIN_DIR, $MAN_DIR, and $ARCH to be set to create default settings for these.
These variables are *always* overwritten by the command line arguments.

### CODE REVIEW

**Comment by aarondill** [comment]
@ajeetdsouza I hope I've accomplished what you expected when we first discussed this (almost a year ago) [here](https://github.com/ajeetdsouza/zoxide/pull/561#issuecomment-1610129741).
If anything is missing, or you have any changes you'd like made, please let me know :smile:

**Comment by rseichter** [comment]
I used the official install script for the first time today, because of the outdated Debian 11 package. Right away I was surprised by the hard-coded `$HOME/.local/{bin,man}` directories. While this was easy enough to fix manually, I would appreciate being able to pass the desired directories (or in my case a directory prefix `/usr/local`) as either a installer script argument or environment variable. I checked the list of Zoxide pull requests and found this one, so I'd like to vote in favour.

**Comment by rseichter** [comment]
Thank you for the new configuration options. They make automation easier for me, and I have already updated my jobs accordingly.

**Comment by ajeetdsouza** [comment]
Thank you @aarondill for the PR.

**Pull request merged**
