### PR TITLE
Add manual score adjustment

### PR DESCRIPTION
**Pull request by TheRealFalcon**
This commit adds '-i' and '-d' options to the 'zoxide add' command.
'-i' increments the base score by a specified amount.
'-d' decrements the base score by a specified amount.

Also added unit tests covering the new functionality combined with
recency scoring.

Fixes/Supports #392

### CODE REVIEW

**Comment by ajeetdsouza** [comment]
Hey @TheRealFalcon, sorry for the delayed reply. I think a feature like this would be very confusing to use.

The working of zoxide's algorithm is explained [here](https://github.com/ajeetdsouza/zoxide/wiki/Algorithm). I see you're setting the `last_accessed` field to `now`, which means that decrementing the rank can actually increase the score. Consider this scenario:

- There's a directory with `{ rank: 100, last_accessed: <last_year> }`. The effective score becomes `rank/4 = 25`.
- When you _decrement_ by `1`, the directory becomes `{ rank: 99, last_accessed: <few_seconds_ago> }`. Now, the score becomes `rank*4 = 396` (!!!)

Even if you changed the function to not edit the `last_accessed` field, it still means that changing the rank by `1` would change the effective score by anywhere between `0.25` and `4`.

I'm closing this PR for this reason, do feel free to comment with your thoughts.

**Comment by TheRealFalcon** [comment]
Are you uninterested in supporting #392 at all, or is the issue just this implementation? If it's the implementation, I could try to change it so it works as you'd like, but if you're against the idea of #392 in general, it'd probably be best to close that issue.

**Comment by TheRealFalcon** [comment]
@ajeetdsouza , thanks for the info. That's certainly something I could work on. I'm assuming #236 would be the best place to discuss details?

**Comment by ajeetdsouza** [comment]
I opened up https://github.com/ajeetdsouza/zoxide/issues/453 with a spec, feel free to discuss there.

**Pull request closed without merging**
