### PR TITLE
Update Nushell script to support engine-q

### LINKED ISSUE #345: Update Nushell script to support engine-q
Nushell is upgrading to a new engine with numerous backward-incompatible changes, which breaks zoxide's initialization script. The script would have to be updated accordingly.

CC @fdncred

### PR DESCRIPTION
**Pull request by ajeetdsouza**
Closes #345.

CC @fennewald I would love a review on this.

### CODE REVIEW

**Comment by ajeetdsouza** [comment]
Update: things are now failing because of:

- https://github.com/nushell/nushell/issues/4899
- https://github.com/nushell/nushell/issues/5175

This is fixed in 0.61.0, we can hopefully merge once this comes to Nixpkgs.

**Comment by fdncred** [comment]
@ajeetdsouza not sure you saw this but jt fixed one of the blocking issues above. https://github.com/nushell/nushell/pull/5271

**Comment by ajeetdsouza** [comment]
@fdncred thanks, I removed the offending comment from the generated code so that we can release with 0.61.0 -- whenever that lands on Nixpkgs.

**Comment by fdncred** [comment]
oh, I thought that already landed https://github.com/NixOS/nixpkgs/pull/169479

**Pull request merged**
