### PR TITLE
Add arch install command

### PR DESCRIPTION
**Pull request by jneidel**

### CODE REVIEW

**Comment by cole-h** [comment]
Thanks! I think we should wait to merge this for after https://github.com/ajeetdsouza/zoxide/pull/54 lays the foundation for adding distro-specific install instructions, whenever the author gets around to it.

Alternatively, you could beat them to it, taking my suggestion over there into account, and we'll just have them rebase when they get around to it.

**Comment by ajeetdsouza** [comment]
Also, do add a version badge for the AUR!

**Comment by ajeetdsouza** [comment]
@jneidel, now that distro-specific installation instructions are being added to the README, would you be able to continue work on this?

**Comment by ajeetdsouza** [comment]
Closing due to inactivity. I've added Arch installation instructions in https://github.com/ajeetdsouza/zoxide/commit/bc0ca7b82c1dd9941ca5c313f40d29c9f7977da8.

Thank you for maintaining zoxide!

**Pull request closed without merging**
